# Generated by Django 5.1.4 on 2026-09-26 18:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, max_length=4000)),
                ('open_at', models.DateTimeField()),
                ('submissions_close_at', models.DateTimeField()),
                ('judging_open_at', models.DateTimeField()),
                ('judging_close_at', models.DateTimeField()),
                ('results_at', models.DateTimeField(blank=True, null=True)),
                ('voting_mode', models.CharField(choices=[('simple', 'Simple'), ('quadratic', 'Quadratic')], default='simple', max_length=20)),
                ('pairwise_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events_event',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('visitor', 'Visitor'), ('participant', 'Participant'), ('judge', 'Judge'), ('organizer', 'Organizer'), ('admin', 'Admin')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_memberships', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events_membership',
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default', max_length=80)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rubric', to='events.event')),
            ],
            options={
                'db_table': 'events_rubric',
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=4)),
                ('min', models.IntegerField(default=1)),
                ('max', models.IntegerField(default=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='events.rubric')),
            ],
            options={
                'db_table': 'events_rubriccriterion',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='events.event')),
            ],
            options={
                'db_table': 'events_track',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='events.event')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='events.track')),
            ],
            options={
                'db_table': 'events_prize',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['slug'], name='events_even_slug_30eb0f_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'event'], name='events_memb_user_id_cc1ed1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('event', 'slug')},
        ),
    ]
