# Generated by Django 5.1.4 on 2026-09-27 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'role'], name='events_memb_user_id_e6ceb9_idx'),
        ),
    ]
