# Generated by Django 5.1.4 on 2026-09-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_membership_events_memb_user_id_e6ceb9_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom_questions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
