# Generated by Django 5.1.4 on 2026-09-26 19:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seed', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviews_per_project', models.IntegerField(default=3)),
                ('projects_per_judge', models.IntegerField(default=4)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_judge_batches', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_batches', to='events.event')),
            ],
            options={
                'db_table': 'judging_judgebatch',
            },
        ),
        migrations.CreateModel(
            name='JudgeAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to='submissions.submission')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='judging.judgebatch')),
            ],
            options={
                'db_table': 'judging_judgeassignment',
            },
        ),
        migrations.CreateModel(
            name='JudgeInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_judge_invites', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_invites', to='events.event')),
            ],
            options={
                'db_table': 'judging_judgeinvite',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='judging.judgeassignment')),
            ],
            options={
                'db_table': 'judging_review',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='judging.judgeassignment')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='events.rubriccriterion')),
            ],
            options={
                'db_table': 'judging_score',
            },
        ),
        migrations.AddIndex(
            model_name='judgebatch',
            index=models.Index(fields=['event', 'created_at'], name='judging_jud_event_i_956eb2_idx'),
        ),
        migrations.AddIndex(
            model_name='judgeassignment',
            index=models.Index(fields=['judge', 'batch'], name='judging_jud_judge_i_19653b_idx'),
        ),
        migrations.AddIndex(
            model_name='judgeassignment',
            index=models.Index(fields=['project'], name='judging_jud_project_b32b02_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='judgeassignment',
            unique_together={('batch', 'judge', 'project')},
        ),
        migrations.AddIndex(
            model_name='judgeinvite',
            index=models.Index(fields=['email'], name='judging_jud_email_f216d0_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['assignment'], name='judging_sco_assignm_bd6ed1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('assignment', 'criterion')},
        ),
    ]
