# Generated by Django 5.1.4 on 2026-09-27 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0001_initial'),
        ('submissions', '0004_remove_comment_submissions_submiss_4c2fe7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='judgeassignment',
            index=models.Index(fields=['judge', 'project'], name='judging_jud_judge_i_815874_idx'),
        ),
    ]
