# Generated by Django 5.1.4 on 2026-09-26 18:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('tagline', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, max_length=8000)),
                ('thumbnail_path', models.CharField(blank=True, max_length=255)),
                ('demo_video_url', models.URLField(blank=True)),
                ('repo_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('locked', 'Locked'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='events.event')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='teams.team')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='events.track')),
            ],
            options={
                'db_table': 'submissions_submission',
                'indexes': [models.Index(fields=['event', 'status', 'track'], name='submissions_event_i_90ca94_idx')],
            },
        ),
    ]
