# Generated by Django 5.1.4 on 2026-09-27 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='submissions_submiss_4c2fe7_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='submissions_submiss_8afe14_idx',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['submission', 'is_hidden', 'created_at'], name='submissions_submiss_47f631_idx'),
        ),
    ]
