# Generated by Django 5.1.4 on 2026-09-28 16:12

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_remove_comment_submissions_submiss_4c2fe7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='tech_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=20),
        ),
        migrations.CreateModel(
            name='SubmissionImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=1000)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='submissions.submission')),
            ],
            options={
                'db_table': 'submissions_submissionimage',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_id', models.CharField(max_length=64)),
                ('value', models.JSONField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='submissions.submission')),
            ],
            options={
                'db_table': 'submissions_submissionanswer',
                'constraints': [models.UniqueConstraint(fields=('submission', 'question_id'), name='unique_answer_per_question')],
            },
        ),
    ]
