# Generated by Django 5.1.4 on 2026-09-26 19:24

import apps.certificates.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=apps.certificates.models.generate_public_id, editable=False, max_length=64, unique=True)),
                ('signed_payload', models.JSONField()),
                ('signature', models.CharField(max_length=64)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='submissions.submission')),
            ],
            options={
                'db_table': 'certificates_certificate',
                'indexes': [models.Index(fields=['public_id'], name='certificate_public__82a823_idx')],
            },
        ),
    ]
