# Generated by Django 5.1.4 on 2026-09-28 16:48

import apps.certificates.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('events', '0003_event_custom_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=apps.certificates.models.generate_public_id, editable=False, max_length=64, unique=True)),
                ('signed_payload', models.JSONField()),
                ('signature', models.CharField(max_length=64)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_certificates', to='events.event')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'certificates_judgecertificate',
                'indexes': [models.Index(fields=['public_id'], name='certificate_public__428783_idx'), models.Index(fields=['event', 'judge'], name='certificate_event_i_7f8394_idx')],
                'constraints': [models.UniqueConstraint(fields=('judge', 'event'), name='unique_judge_event_certificate')],
            },
        ),
    ]
