# Generated by Django 5.1.4 on 2026-09-28 17:03

import apps.certificates.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('events', '0003_event_custom_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=apps.certificates.models.generate_public_id, editable=False, max_length=64, unique=True)),
                ('signed_payload', models.JSONField()),
                ('signature', models.CharField(max_length=64)),
                ('issued_at', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_records', to='events.event')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_judge_records', to=settings.AUTH_USER_MODEL)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'certificates_judgerecord',
                'indexes': [models.Index(fields=['public_id'], name='certificate_public__8f347f_idx'), models.Index(fields=['event', 'judge'], name='certificate_event_i_558808_idx')],
            },
        ),
    ]
