# Generated by Django 5.1.4 on 2026-09-28 16:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('success', models.BooleanField(default=False)),
                ('response_body', models.TextField(blank=True, default='')),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api.webhook')),
            ],
            options={
                'db_table': 'api_webhookdelivery',
                'indexes': [models.Index(fields=['webhook', '-created_at'], name='api_webhook_webhook_9ca5f3_idx'), models.Index(fields=['event_type', 'success'], name='api_webhook_event_t_75cb3c_idx')],
            },
        ),
    ]
