# Generated by Django 5.1.4 on 2026-09-27 05:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('display_name', models.CharField(max_length=80)),
                ('monthly_price_cents', models.IntegerField(default=0)),
                ('max_events', models.IntegerField(blank=True, null=True)),
                ('max_judges_per_event', models.IntegerField(blank=True, null=True)),
                ('max_submissions_per_event', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billing_plan',
                'ordering': ['monthly_price_cents'],
            },
        ),
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled')], default='trial', max_length=12)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='events.event')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='billing.plan')),
            ],
            options={
                'db_table': 'billing_billingaccount',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('charge', 'Charge'), ('refund', 'Refund'), ('plan_change', 'Plan Change'), ('adjustment', 'Adjustment')], max_length=12)),
                ('amount_cents', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.billingaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_invoice',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'created_at'], name='billing_inv_account_34f07b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='billingaccount',
            index=models.Index(fields=['plan', 'status'], name='billing_bil_plan_id_564f98_idx'),
        ),
    ]
