# Generated by Django 5.1.4 on 2026-09-26 19:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=100)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('raw_sigma', models.FloatField()),
                ('normalized_sigma', models.FloatField()),
                ('is_connected', models.BooleanField()),
                ('iterations', models.IntegerField(default=0)),
                ('n_reviews', models.IntegerField(default=0)),
                ('n_projects', models.IntegerField(default=0)),
                ('n_judges', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proof_text', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalization_runs', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalization_runs', to='events.event')),
            ],
            options={
                'db_table': 'normalization_normalizationrun',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JudgeBias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judge_id', models.CharField(max_length=64)),
                ('bias', models.FloatField()),
                ('n_reviews', models.IntegerField()),
                ('leverage', models.FloatField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biases', to='normalization.normalizationrun')),
            ],
            options={
                'db_table': 'normalization_judgebias',
            },
        ),
        migrations.CreateModel(
            name='NormalizedScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=64)),
                ('raw_mean', models.FloatField()),
                ('adjusted', models.FloatField()),
                ('rank_before', models.IntegerField()),
                ('rank_after', models.IntegerField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='normalization.normalizationrun')),
            ],
            options={
                'db_table': 'normalization_normalizedscore',
            },
        ),
        migrations.AddIndex(
            model_name='normalizationrun',
            index=models.Index(fields=['event', 'created_at'], name='normalizati_event_i_5ecea0_idx'),
        ),
        migrations.AddIndex(
            model_name='judgebias',
            index=models.Index(fields=['run', 'judge_id'], name='normalizati_run_id_8826ec_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedscore',
            index=models.Index(fields=['run', 'project_id'], name='normalizati_run_id_d00626_idx'),
        ),
    ]
