# Generated by Django 5.1.4 on 2026-09-28 16:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload_type', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('status', models.CharField(default='pending', max_length=16)),
                ('response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api.webhook')),
            ],
            options={
                'db_table': 'webhooks_webhookdelivery',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['webhook', '-created_at'], name='webhooks_we_webhook_8d7634_idx'), models.Index(fields=['status'], name='webhooks_we_status_6d768a_idx')],
            },
        ),
    ]
