# Generated by Django 5.1.4 on 2026-09-26 19:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PairwiseRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(default='bradley_terry_mm', max_length=50)),
                ('n_ballots', models.PositiveIntegerField(default=0)),
                ('iterations', models.PositiveIntegerField(default=0)),
                ('converged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_pairwise_runs', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairwise_runs', to='events.event')),
            ],
            options={
                'db_table': 'pairwise_pairwiserun',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PairwiseRanking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theta', models.FloatField()),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('ties', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairwise_rankings', to='submissions.submission')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='pairwise.pairwiserun')),
            ],
            options={
                'db_table': 'pairwise_pairwiseranking',
                'ordering': ['run', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='PairwiseBallot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voter_key', models.CharField(help_text="Identifier of the voter -- user UUID, session token, or 'community:<ip>' for public votes.", max_length=128)),
                ('winner', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('tie', 'Tie')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairwise_ballots', to='events.event')),
                ('left_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairwise_ballots_as_left', to='submissions.submission')),
                ('right_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairwise_ballots_as_right', to='submissions.submission')),
            ],
            options={
                'db_table': 'pairwise_pairwiseballot',
                'indexes': [models.Index(fields=['event', 'left_project', 'right_project'], name='pairwise_pa_event_i_af63e1_idx'), models.Index(fields=['event', 'voter_key'], name='pairwise_pa_event_i_144b74_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pairwiserun',
            index=models.Index(fields=['event', 'created_at'], name='pairwise_pa_event_i_cca4a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pairwiseranking',
            unique_together={('run', 'project')},
        ),
    ]
