# Generated by Django 5.1.4 on 2026-09-26 19:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voter_key', models.CharField(max_length=64)),
                ('voter_email_hash', models.CharField(blank=True, max_length=64)),
                ('votes', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retracted_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='events.event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='submissions.submission')),
                ('voter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voting_vote',
            },
        ),
        migrations.CreateModel(
            name='VoteAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('cast', 'Cast'), ('retract', 'Retract')], max_length=10)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='voting.vote')),
            ],
            options={
                'db_table': 'voting_voteaudit',
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='VoteBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_key', models.CharField(max_length=64)),
                ('spent_credits', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_budgets', to='events.event')),
            ],
            options={
                'db_table': 'voting_votebudget',
            },
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['event', 'voter_key'], name='voting_vote_event_i_bb761e_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['event', 'project'], name='voting_vote_event_i_2be038_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('event', 'project', 'voter_key')},
        ),
        migrations.AddIndex(
            model_name='voteaudit',
            index=models.Index(fields=['vote', 'action'], name='voting_vote_vote_id_2ffa46_idx'),
        ),
        migrations.AddIndex(
            model_name='voteaudit',
            index=models.Index(fields=['at'], name='voting_vote_at_0facc0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='votebudget',
            unique_together={('event', 'voter_key')},
        ),
    ]
