# Generated by Django 5.1.4 on 2026-09-26 19:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('upheld', 'Upheld'), ('dismissed', 'Dismissed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolver_note', models.CharField(blank=True, max_length=400)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abuse_flags', to=settings.AUTH_USER_MODEL)),
                ('resolver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_abuse_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'abuse_abuseflag',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='abuse_abuse_target__be1916_idx'), models.Index(fields=['status'], name='abuse_abuse_status_862c62_idx'), models.Index(fields=['created_at'], name='abuse_abuse_created_f7a7aa_idx')],
            },
        ),
    ]
